# Generated by Django 4.1.4 on 2022-12-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nombre_livre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenerateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('serveur', models.CharField(choices=[('seasonskyV3', 'seasonskyV3')], max_length=100)),
                ('theme', models.CharField(choices=[('default', 'default'), ('noel', 'noel')], max_length=100)),
                ('taille', models.IntegerField(choices=[(4, 4), (5, 5), (6, 6)], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('serveur', models.CharField(choices=[('', 'Sélectionnez'), ('seasonskyV3', 'seasonskyV3')], max_length=100)),
                ('theme', models.CharField(choices=[('', 'Sélectionnez'), ('default', 'default'), ('noel', 'noel')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('nombres_pages', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
                ('bibliotheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ours.biblio')),
            ],
        ),
    ]
